### ISSUE TITLE
Add integration-test using testcontainers

### ISSUE THREAD

**Issue by apollo-pablo** [apollodao/cw-dex#89]
> Problem

We need to do some integration test on pseudo real chain ( not mock ). We will use testcontainer and the integration-test-framework

> Tasks

- [ ] Add Integration test to Terra.
- [ ] Add Integration test to Juno.
- [ ] Add Integration test to Osmosis.

**Comment by apollo-sturdy** [comment]
There are some issues with this. Mainly that we can't reuse the same tests for the bindings and testcontainers. If we want to do this we should write a macro so we don't have to copy-paste all of the tests. We should also set up the CI so that the tests against testcontainers only run on merge to master and not on every PR into develop, since the tests against testcontainers take a lot of time.
